[package]
name = "ngkv"
version = "0.1.0"
authors = ["zhongjn <zhongjn0@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
once_cell = "1.5.2"

[dev-dependencies]
mockall = "0.9.0"